### ISSUE TITLE
Yahoo Finance has apparently killed its API

### ISSUE THREAD

**Issue by spk** [scottjbarr/yahoo_currency#2]
Currently this url http://download.finance.yahoo.com/d/quotes.csv?s=AUDUSD=X&f=nl1d1t1 gives a 403 with

```It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.```

Maybe endpoint should be changed, there is alternative on https://news.ycombinator.com/item?id=15616880
Like https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote?format=json

**Comment by scottjbarr** [comment]
Oh right, I forgot about that change. Such a shame. I always found the Yahoo Finance API useful.

Happy to take a PR.

**Comment by ROBERT-MCDOWELL** [comment]
https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote?format=json
does not work anymore since 1 month. Couldn't find their new link.
If any find it please comment thanks

**Comment by scottjbarr** [comment]
Yahoo have killed off their finance API unfortunately.

**Comment by ROBERT-MCDOWELL** [comment]
found a better one
www.apilayer.com

**Comment by scottjbarr** [comment]
Their API looks decent. Worth building a client for, if one can't be found.

The Yahoo Finance API was always a bit rough. It wasn't publicly documented, but you could get good results out of it. I'm not sad to see it be replaced by good quality services.

**Comment by ROBERT-MCDOWELL** [comment]
yes indeed, they have also responsive support apparently
